import { access, cors, createDelivery, driveToken } from "./_shared.js";
export default async function handler(req,res) {
  cors(req,res); if(req.method==="OPTIONS") return res.status(200).end(); if(req.method!=="POST") return res.status(405).json({ok:false,message:"Método no permitido."});
  try {
    const explicacion=String(req.body?.respuestaExplicacion||"").trim(), fileId=String(req.body?.driveFileId||""), token=String(req.body?.uploadToken||""); if(!explicacion||!fileId||!token) return res.status(400).json({ok:false,message:"Faltan datos para confirmar la entrega."});
    const {sql,estudiante}=await access(req.body.idToken); const pending=await sql`SELECT * FROM entregas_upload_pendientes WHERE token=${token} AND estudiante_id=${estudiante.id} AND actividad_id=${estudiante.actividad_id} AND creado_en > now()-interval '1 hour' LIMIT 1`; if(!pending.length) return res.status(404).json({ok:false,message:"La sesión de subida no existe o venció."});
    const item=pending[0], auth=await driveToken(); const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?fields=id,name,mimeType,size,parents`,{headers:{Authorization:`Bearer ${auth}`}}); const file=await response.json(); if(!response.ok||file.id!==fileId||file.name!==item.nombre_drive||!file.parents?.includes(item.drive_folder_id)||Number(file.size)!==Number(item.tamanio_bytes)) return res.status(400).json({ok:false,message:"Drive no confirmó el archivo esperado."});
    const entrega=await createDelivery(sql,{estudianteId:estudiante.id,actividadId:estudiante.actividad_id,numeroEjercicio:item.numero_ejercicio,tipo:"archivo",explicacion}); await sql`INSERT INTO archivos_entrega (entrega_id,drive_file_id,nombre_original,nombre_drive,mime_type,extension,tamanio_bytes) VALUES (${entrega[0].id},${file.id},${item.nombre_original},${file.name},${file.mimeType||item.mime_type},${item.extension},${item.tamanio_bytes})`; await sql`DELETE FROM entregas_upload_pendientes WHERE token=${token}`;
    return res.status(201).json({ok:true,entrega:entrega[0]});
  } catch(error) { return res.status(error.status||500).json({ok:false,message:error.message||"No se pudo confirmar la entrega."}); }
}
